// Builds the identity matrix's baseline for one slice from its parent commit, in a throwaway
// `git worktree`, and writes test/fixtures/identity/<slice>.json.
//
//   node test/lib/build_identity_baseline.mjs S0 9f0136e
//
// For every shape in test/lib/identityshapes.js the parent engine is built (the parent's own
// main/build/pipeline.js, on a project generated by *this* tree), and the ROM's hash, size and
// (for a shape that assembles move_face) the old move_face/move_face_player addresses are stored.
// A second pass builds the same shapes with the parent's move_face padded by 24 bytes at the
// place S0 inserts its clamp: that ROM, with the padding blanked, and its symbol table are what S0's
// own ROM must match (test/lib/identitycompare.js explains why). The worktree is removed afterwards;
// nothing in this tree is written but the fixture file.
//
// S1+ baselines are their parent slice's builds: run this again with that slice's parent rev.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { saveProject } from '../../main/project-io.js';
import { SHAPES, buildShapeProject } from './identityshapes.js';
import { sha256, parseFns, symbolsHash, kernelFileOffset, blankedHash, CLAMP_BYTES } from './identitycompare.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const [slice, rev] = process.argv.slice(2);
if (!slice || !rev) {
  process.stderr.write('usage: node test/lib/build_identity_baseline.mjs <slice> <parent-rev>\n');
  process.exit(1);
}
const git = (...args) => execFileSync('git', args, { cwd: ROOT, stdio: ['ignore', 'pipe', 'inherit'] }).toString().trim();
const fullRev = git('rev-parse', '--verify', `${rev}^{commit}`);
const wt = fs.mkdtempSync(path.join(os.tmpdir(), 'identity-baseline-'));
fs.rmSync(wt, { recursive: true });
git('worktree', 'add', '--detach', wt, fullRev);

try {
  fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(wt, 'node_modules'), 'dir');
  const { buildProject } = await import(pathToFileURL(path.join(wt, 'main/build/pipeline.js')));
  const generate = await import(pathToFileURL(path.join(wt, 'main/build/generate.js')));

  async function buildAll(only) {
    const out = {};
    for (const shape of SHAPES) {
      if (only && !only.has(shape.id)) continue;
      const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'identity-shape-'));
      try {
        const project = buildShapeProject(shape.desc);
        await saveProject(dir, project);
        const built = await buildProject({ dir, project, log: () => {} });
        out[shape.id] = {
          rom: new Uint8Array(fs.readFileSync(built.romPath)),
          syms: parseFns(fs.readFileSync(path.join(dir, 'build/game.fns'), 'utf8'))
        };
      } finally {
        fs.rmSync(dir, { recursive: true, force: true });
      }
    }
    return out;
  }

  const parent = await buildAll();
  const result = {};
  const faceShapes = new Set();
  for (const [id, { rom, syms }] of Object.entries(parent)) {
    result[id] = { romSha: sha256(rom), size: rom.length };
    if (syms.move_face !== undefined) {
      faceShapes.add(id);
      result[id].oldMoveFace = syms.move_face;
      result[id].oldMoveFacePlayer = syms.move_face_player;
    }
  }

  // second pass: the parent's move_face with 24 padding bytes where S0 puts its clamp
  const entitiesPath = path.join(wt, 'engine/entities.asm');
  const original = fs.readFileSync(entitiesPath, 'utf8');
  const anchor = '  ldx <talk_ent\n  sta ent_dir,x\n  rts\nmove_face_player:';
  if (original.split(anchor).length !== 2) throw new Error('move_face anchor not found exactly once in the parent engine');
  const pad = `  ldx <talk_ent\n  sta ent_dir,x\nmove_face_pad:\n${'  .db $00,$00,$00,$00,$00,$00,$00,$00\n'.repeat(3)}move_face_done:\n  rts\nmove_face_player:`;
  fs.writeFileSync(entitiesPath, original.replace(anchor, pad));
  const padded = await buildAll(faceShapes);
  fs.writeFileSync(entitiesPath, original);
  for (const [id, { rom, syms }] of Object.entries(padded)) {
    if (syms.move_face_done - syms.move_face_pad !== CLAMP_BYTES) throw new Error(`${id}: the padding is not ${CLAMP_BYTES} bytes`);
    result[id].blankedSha = blankedHash(rom, kernelFileOffset(rom, syms.move_face_pad));
    result[id].paddedSize = rom.length;
    result[id].symbolsSha = symbolsHash(syms, ['move_face_pad']);
  }

  const file = path.join(ROOT, 'test/fixtures/identity', `${slice}.json`);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify({ slice, parentRev: fullRev, baselineFaceAllowance: generate.FACE_KERNEL_ALLOWANCE, shapes: result }, null, 2)}\n`);
  process.stdout.write(`wrote ${path.relative(ROOT, file)}: ${Object.keys(result).length} shapes, ${faceShapes.size} with move_face\n`);
} finally {
  execFileSync('git', ['worktree', 'remove', '--force', wt], { cwd: ROOT, stdio: 'ignore' });
}
