// Builds the identity matrix's baseline for one slice from its parent commit, in a throwaway
// `git worktree`, and writes test/fixtures/identity/<slice>.json.
//
//   node test/lib/build_identity_baseline.mjs S1 99d4156
//
// For every shape in test/lib/identityshapes.js the parent engine is built (the parent's own
// main/build/pipeline.js, on a project generated by *this* tree) and recorded:
//   romSha, size     the ROM itself -- an ordinary-only shape must still equal it (S1-I1)
//   namesSha         a hash of the sorted symbol NAMES, so the test can prove the symbol diff is
//                    exactly the expected added/removed set without storing thousands of names
//   klAnchor/khAnchor the addresses of the last kernel-lo (music_tick_loop) and last kernel-hi
//                    (sw_redraw_screen_landing_end) labels: how far each region grew
//   showSw           draw_one_entity_show_sw's span size and a hash of its normalised
//                    instructions and relocations (test/lib/identitycompare.js normalizeSpan)
//   moveFace         move_face's address, where the shape assembles it
// The worktree is removed afterwards; nothing in this tree is written but the fixture file.
// Slice N+1's baseline is slice N's builds: run this again with that slice's parent rev.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { saveProject } from '../../main/project-io.js';
import { SHAPES, buildShapeProject } from './identityshapes.js';
import { sha256, parseFns, namesHash, normalizeSpan } from './identitycompare.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const [slice, rev] = process.argv.slice(2);
if (!slice || !rev) {
  process.stderr.write('usage: node test/lib/build_identity_baseline.mjs <slice> <parent-rev>\n');
  process.exit(1);
}
const git = (...args) => execFileSync('git', args, { cwd: ROOT, stdio: ['ignore', 'pipe', 'inherit'] }).toString().trim();
const fullRev = git('rev-parse', '--verify', `${rev}^{commit}`);
const wt = fs.mkdtempSync(path.join(os.tmpdir(), 'identity-baseline-'));
fs.rmSync(wt, { recursive: true });
git('worktree', 'add', '--detach', wt, fullRev);

try {
  fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(wt, 'node_modules'), 'dir');
  const { buildProject } = await import(pathToFileURL(path.join(wt, 'main/build/pipeline.js')));
  const result = {};
  for (const shape of SHAPES) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'identity-shape-'));
    try {
      const project = buildShapeProject(shape.desc);
      await saveProject(dir, project);
      const built = await buildProject({ dir, project, log: () => {} });
      const rom = new Uint8Array(fs.readFileSync(built.romPath));
      const syms = parseFns(fs.readFileSync(path.join(dir, 'build/game.fns'), 'utf8'));
      const entry = {
        romSha: sha256(rom),
        size: rom.length,
        namesSha: namesHash(syms),
        klAnchor: syms.music_tick_loop
      };
      if (syms.sw_redraw_screen_landing_end !== undefined) entry.khAnchor = syms.sw_redraw_screen_landing_end;
      if (syms.draw_one_entity_show_sw !== undefined) {
        const lines = normalizeSpan(rom, syms, 'draw_one_entity_show_sw', 'draw_one_entity_show_sw_end');
        entry.showSw = {
          size: syms.draw_one_entity_show_sw_end - syms.draw_one_entity_show_sw,
          instructions: lines.length,
          normSha: sha256(lines.join('\n'))
        };
      }
      if (syms.move_face !== undefined) entry.moveFace = syms.move_face;
      result[shape.id] = entry;
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }
  const file = path.join(ROOT, 'test/fixtures/identity', `${slice}.json`);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify({ slice, parentRev: fullRev, shapes: result }, null, 2)}\n`);
  process.stdout.write(`wrote ${path.relative(ROOT, file)}: ${Object.keys(result).length} shapes\n`);
} finally {
  execFileSync('git', ['worktree', 'remove', '--force', wt], { cwd: ROOT, stdio: 'ignore' });
}
