// Builds the identity matrix's baseline for one slice from its parent commit, in a throwaway
// `git worktree`, and writes test/fixtures/identity/<slice>.json.
//
//   node test/lib/build_identity_baseline.mjs S1 99d4156
//   node test/lib/build_identity_baseline.mjs S3a 3313b62 --carry-s3a5
//   node test/lib/build_identity_baseline.mjs S3b 15c11b7 --carry-overrun --carry-backdrop
//
// --carry-overrun (Say/Move overrun fix): the parent's streamdialog.asm, chunk read, shim body and close-row alias bytes are
// replaced by the CURRENT ones (carryOverrunLever / carryOverrunConstants), so "identical to the parent" still means what it
// did for every build that streams text; the close row itself is held by streamdialogclose.test.js's independent oracle.
//
// --carry-backdrop (Phase 3b S0): the parent's engine/battle.asm and engine/battleturn.asm are replaced by the CURRENT ones, so
// the battle backdrop fix (draw_battle_screen/wipe_monster read cur_map under STREAMING_ENABLED) is in both builds. It changes every
// streamed RPG ROM by construction, so "identical to the parent" would otherwise be false for each of them; a non-streamed ROM never
// assembled the changed lines, and the backdrop itself is held by streamedbackdrop.test.js's own nametable oracle. The two files have
// no other difference between 15c11b7 and the slice (git diff is empty), so lifting them whole carries exactly the fix.
//
// --carry-s3a5 (Phase 3a S3a.5): the parent's sw_camera_window_recompute is replaced by the CURRENT closed-form
// camera (carryS3a5Lever, test/lib/enginehistory.js) before it is built, and the file records `carries`. S3a.5
// made every streamed ROM differ from every earlier commit's in that one routine and the kernel-hi addresses
// after it, so "identical to the parent" would otherwise be false for every streamed shape; the baseline then
// says "the parent plus the lever", and the camera rule itself is held by streamworldcamera.test.js.
//
// For every shape in test/lib/identityshapes.js the parent engine is built (the parent's own
// main/build/pipeline.js, on a project generated by *this* tree) and recorded:
//   romSha, size     the ROM itself -- an ordinary-only shape must still equal it (S1-I1)
//   namesSha         a hash of the sorted symbol NAMES, so the test can prove the symbol diff is
//                    exactly the expected added/removed set without storing thousands of names
//   klAnchor/khAnchor the addresses of the last kernel-lo (music_tick_loop) and last kernel-hi
//                    (sw_redraw_screen_landing_end) labels: how far each region grew
//   showSw           draw_one_entity_show_sw's span size and a hash of its normalised
//                    instructions and relocations (test/lib/identitycompare.js normalizeSpan)
//   moveFace         move_face's address, where the shape assembles it
// The worktree is removed afterwards; nothing in this tree is written but the fixture file.
// Slice N+1's baseline is slice N's builds: run this again with that slice's parent rev.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { saveProject } from '../../main/project-io.js';
import { SHAPES, buildShapeProject } from './identityshapes.js';
import { sha256, parseFns, namesHash, normalizeSpan } from './identitycompare.js';
import { carryS3a5Lever, carryOverrunLever, carryOverrunConstants } from './enginehistory.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const carryLever = process.argv.includes('--carry-s3a5');
const carryOverrun = process.argv.includes('--carry-overrun');
const carryBackdrop = process.argv.includes('--carry-backdrop');
const [slice, rev] = process.argv.slice(2).filter((a) => !a.startsWith('--'));
if (!slice || !rev) {
  process.stderr.write('usage: node test/lib/build_identity_baseline.mjs <slice> <parent-rev>\n');
  process.exit(1);
}
const git = (...args) => execFileSync('git', args, { cwd: ROOT, stdio: ['ignore', 'pipe', 'inherit'] }).toString().trim();
const fullRev = git('rev-parse', '--verify', `${rev}^{commit}`);
const wt = fs.mkdtempSync(path.join(os.tmpdir(), 'identity-baseline-'));
fs.rmSync(wt, { recursive: true });
git('worktree', 'add', '--detach', wt, fullRev);

try {
  fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(wt, 'node_modules'), 'dir');
  if (carryLever) {
    const at = path.join(wt, 'engine/streamworld.asm');
    fs.writeFileSync(at, carryS3a5Lever(fs.readFileSync(at, 'utf8'), fs.readFileSync(path.join(ROOT, 'engine/streamworld.asm'), 'utf8')));
  }
  if (carryOverrun) {
    // the Say/Move overrun fix: the CURRENT close row, its chunk read and its alias bytes, lifted into the parent
    const read = (root, name) => fs.readFileSync(path.join(root, 'engine', name), 'utf8');
    const put = (name, text) => fs.writeFileSync(path.join(wt, 'engine', name), text);
    put('streamworld.asm', carryOverrunLever(read(wt, 'streamworld.asm'), read(ROOT, 'streamworld.asm')));
    put('streamdialog.asm', read(ROOT, 'streamdialog.asm'));
    put('constants.asm', carryOverrunConstants(read(wt, 'constants.asm'), read(ROOT, 'constants.asm')));
  }
  if (carryBackdrop) {
    for (const name of ['battle.asm', 'battleturn.asm']) {
      fs.writeFileSync(path.join(wt, 'engine', name), fs.readFileSync(path.join(ROOT, 'engine', name), 'utf8'));
    }
  }
  const { buildProject } = await import(pathToFileURL(path.join(wt, 'main/build/pipeline.js')));
  const result = {};
  for (const shape of SHAPES) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'identity-shape-'));
    try {
      const project = buildShapeProject(shape.desc);
      await saveProject(dir, project);
      const built = await buildProject({ dir, project, log: () => {} });
      const rom = new Uint8Array(fs.readFileSync(built.romPath));
      const syms = parseFns(fs.readFileSync(path.join(dir, 'build/game.fns'), 'utf8'));
      const entry = {
        romSha: sha256(rom),
        size: rom.length,
        namesSha: namesHash(syms),
        klAnchor: syms.music_tick_loop
      };
      if (syms.sw_redraw_screen_landing_end !== undefined) entry.khAnchor = syms.sw_redraw_screen_landing_end;
      if (syms.draw_one_entity_show_sw !== undefined) {
        const lines = normalizeSpan(rom, syms, 'draw_one_entity_show_sw', 'draw_one_entity_show_sw_end');
        entry.showSw = {
          size: syms.draw_one_entity_show_sw_end - syms.draw_one_entity_show_sw,
          instructions: lines.length,
          normSha: sha256(lines.join('\n'))
        };
      }
      if (syms.move_face !== undefined) entry.moveFace = syms.move_face;
      result[shape.id] = entry;
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }
  const file = path.join(ROOT, 'test/fixtures/identity', `${slice}.json`);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify({ slice, parentRev: fullRev, ...(carryLever ? { carries: 's3a5-lever' } : {}), ...(carryOverrun ? { carries: carryBackdrop ? 'overrun-lever+backdrop' : 'overrun-lever' } : {}), shapes: result }, null, 2)}\n`);
  process.stdout.write(`wrote ${path.relative(ROOT, file)}: ${Object.keys(result).length} shapes\n`);
} finally {
  execFileSync('git', ['worktree', 'remove', '--force', wt], { cwd: ROOT, stdio: 'ignore' });
}
