// Code Forge: the escape hatch. Every source file that goes into the ROM, in a
// tree on the left and tabbed editors on the right.
//
// Three kinds of file, and the difference between them is the whole design:
//
//  - **Engine** files are the app's own 6502 sources. Editing one does not touch
//    them: the edit is saved into the *project* as an override, and the build
//    lays it over the stock copy. So one project's custom code cannot leak into
//    another, and reverting is deleting the copy.
//  - **Your files** are new sources the project owns outright. The generator
//    lists them in assets/usercode.inc, which engine/main.asm includes in the
//    fixed kernel — so a label defined here can be called from anywhere.
//  - **Generated** files are the build's own output, read-only because the next
//    build deletes and rewrites the whole folder.
//
// Edits live in `store.project.code`, which is what gives them undo, the dirty
// dot and saving without inventing a second version of any of it. A code editor
// never blurs, so instead of committing per keystroke (an unusable undo stack)
// or on blur (a commit that may never come), typing commits once it pauses.

import { store } from '../../store.js';
import { el, fill, toast, confirmModal, promptModal } from '../../ui.js';
import { CODE_FILE_RE, CODE_LIMITS } from '../../../shared/project.js';
import { createEditor } from './editor.js';

/** How long typing has to pause before it becomes one undo entry. */
const COMMIT_DELAY = 600;

const HINTS = {
  stock:
    'Editing this makes a copy inside your project. The app’s own engine is left alone, and you can ' +
    'revert to the original at any time.',
  override: 'Your project’s copy of this engine file. The build uses this instead of the original.',
  user:
    'Your own code, assembled into the fixed bank at $C000. Call a label in here with jsr from any ' +
    'engine file you have edited.',
  generated: 'Generated by the build from your project. Read-only — the next build rewrites it.',
  original: 'The engine’s original, read-only. Your project’s copy is what the build uses.'
};

// Read-only, never-committed tab kinds, and the word each puts in its own tab
// strip title -- one map backing `isReference`, the title suffix, the
// generic editor's readOnly/onChange wiring in `ensureTab`, and the
// dirty/flush/close/sync-skip checks that use `isReference`. It does not
// decide the stock badge, the stock hint text or the stock-only prune in
// `onProjectChange` -- those stay stock-specific by design (a `generated`
// tab has no override to prune against, and needs no badge since it is never
// shown beside anything it could be confused with).
const REFERENCE_LABELS = { generated: 'generated', stock: 'original' };
const isReference = (tab) => tab.kind in REFERENCE_LABELS;

// The split ratio survives leaving the Code Forge and returning within one
// session -- module-level rather than a `mount()` local -- but is never
// written to the project or to settings, so it does not round-trip through
// save/load and does not appear in undo history.
let splitRatio = 0.5;

export function mount(container, app) {
  // Stock engine sources, fetched once each and kept for the session: they are
  // read-only inputs that cannot change while the app runs, and comparing
  // against them is how an override knows whether it still differs.
  const stockText = new Map();
  let engineFiles = [];
  let generatedFiles = [];

  /** Open tabs, in strip order. */
  const tabs = [];
  // Set by destroy(); every continuation past an `await` in `ensureTab` and
  // `compareWithStock` checks it before touching `tabs` or the panes, since
  // the closures those `await`s resume into outlive nothing on their own --
  // the Forge can be torn down while a fetch is in flight. Not "the DOM"
  // generally: `ensureTab`'s own `catch` still toasts a failed load before
  // this is ever checked, since the error itself is real regardless of
  // whether the Forge that started the load is still mounted to show it in.
  let destroyed = false;
  // One in-flight load promise per tab key, so two clicks before the first
  // resolves share the one fetch/creation rather than each starting its own.
  // Today `ensureTab`'s own post-await `tabByKey` recheck is *also* enough on
  // its own to stop a duplicate -- the check-and-push tail after `loadText`
  // resolves has no further `await` in it, and JS runs that tail to
  // completion, so whichever of two racing loads resolves first finishes
  // creating and pushing its tab before the other's continuation can run.
  // This map is what keeps that true if anyone ever adds an `await` inside
  // that tail -- the recheck alone would stop protecting against a duplicate
  // the moment it did, and the two racing loads would go back to reaching
  // the network/IPC layer twice for the same file besides.
  const pendingLoads = new Map();
  // Bumped once per `compareWithStock` call, at entry -- the last call in
  // wins. A compare in progress reads its own value back after its awaits to
  // tell "I am still the one that should place my panes" from "a later
  // compare (this file or another) started since and owns the panes now".
  let compareSeq = 0;
  // `activeKey` is the primary (left) pane's tab; `splitKey` is the second
  // (right) pane's, or null when the Forge shows a single editor -- which is
  // the only state before this item and must keep behaving exactly as before.
  let activeKey = null;
  let splitKey = null;
  // Which pane a fresh open (a tree click, or the Build panel's error deep
  // link) lands in: whichever pane's textarea last held focus. Defaults to
  // 'left' and is only ever read as 'right' while a split is actually showing
  // (see pickTargetPane), so single-pane behavior never depends on this.
  let focusedPane = 'left';

  const treeHost = el('div.code-tree');
  const tabsHost = el('div.tabs.code-tabs');
  const leftHint = el('div.code-hint');
  const leftHost = el('div.code-host');
  const rightHint = el('div.code-hint');
  const rightHost = el('div.code-host');
  const leftPane = el('div.code-pane', null, leftHint, leftHost);
  const rightPane = el('div.code-pane', { hidden: true }, rightHint, rightHost);
  const divider = el('div.code-divider', { hidden: true });
  const panesHost = el('div.code-panes', null, leftPane, divider, rightPane);

  leftHost.addEventListener('focusin', () => {
    focusedPane = 'left';
  });
  rightHost.addEventListener('focusin', () => {
    focusedPane = 'right';
  });

  /** Apply `splitRatio` as the left pane's flex-basis, or clear it while single. */
  function applySplitRatio() {
    leftPane.style.flex = splitKey ? `0 0 ${splitRatio * 100}%` : '';
  }

  // Defence, not a fix for a reproduced bug: review round 1 found no real
  // trusted pointer whose capture actually fails here (a genuine pointerdown
  // has an active pointer and active buttons, and nothing in this renderer
  // ever takes the pointer lock), only a synthetic-dispatch case. These
  // exist anyway because the cost is a few `removeEventListener` calls and
  // the alternative -- a capture silently lost with only divider-local
  // handlers watching -- is a stuck `dragging` class that blocks every
  // pointer event on both editors (`app.css`'s `.code-panes.dragging
  // .code-pane` rule) until the next drag.
  function stopWindowDragListeners() {
    window.removeEventListener('pointerup', endDrag);
    window.removeEventListener('pointercancel', endDrag);
  }
  function endDrag(event) {
    if (!panesHost.classList.contains('dragging')) return;
    panesHost.classList.remove('dragging');
    if (event && event.pointerId !== undefined) {
      try {
        divider.releasePointerCapture(event.pointerId);
      } catch {
        /* nothing was actually captured, or it was already released */
      }
    }
    stopWindowDragListeners();
  }
  divider.addEventListener('pointerdown', (event) => {
    // A synthetic pointer (as a test dispatches) has no real active pointer
    // behind it, and capture on one throws -- harmless to the drag itself,
    // since `dragging` on panesHost is what pointermove actually gates on.
    try {
      divider.setPointerCapture(event.pointerId);
    } catch {
      /* no real pointer behind this id */
    }
    panesHost.classList.add('dragging');
    // Registered here and removed in endDrag (and in destroy(), belt and
    // braces for a drag still open when the Forge unmounts) rather than left
    // permanently attached, so nothing on `window` outlives this Forge.
    window.addEventListener('pointerup', endDrag);
    window.addEventListener('pointercancel', endDrag);
  });
  divider.addEventListener('pointermove', (event) => {
    if (!panesHost.classList.contains('dragging')) return;
    const rect = panesHost.getBoundingClientRect();
    const ratio = (event.clientX - rect.left) / rect.width;
    splitRatio = Math.min(0.8, Math.max(0.2, ratio));
    applySplitRatio();
  });
  divider.addEventListener('pointerup', endDrag);
  divider.addEventListener('pointercancel', endDrag);
  divider.addEventListener('lostpointercapture', endDrag);
  divider.addEventListener('dblclick', () => {
    splitRatio = 0.5;
    applySplitRatio();
  });

  const codeSlice = () => store.project?.code ?? { overrides: [], files: [] };
  const findFile = (group, name) => codeSlice()[group].find((file) => file.name === name) ?? null;
  const tabKey = (kind, name) => `${kind}:${name}`;
  const tabByKey = (key) => tabs.find((tab) => tabKey(tab.kind, tab.name) === key) ?? null;
  const activeTab = () => tabByKey(activeKey);

  // A buffer that has diverged from what is committed is the tab strip's dot and
  // the shell's unsaved work — one predicate, so the dot and the close guard
  // cannot disagree about whether typing is at risk.
  const tabDirty = (tab) => !isReference(tab) && tab.editor.getValue() !== tab.committed;
  const notePending = () => app.notePendingEdits?.();

  // ------------------------------------------------------------ file access

  async function readStock(name) {
    if (stockText.has(name)) return stockText.get(name);
    const response = await fetch(`forge://app/engine/${name}`);
    if (!response.ok) throw new Error(`Could not read the engine's ${name}.`);
    const text = await response.text();
    stockText.set(name, text);
    return text;
  }

  /** The text a tab should show. Whether the user may edit it is `ensureTab`'s
   * call, from the same `REFERENCE_LABELS` map named at its own declaration
   * above -- not everything about a read-only kind (the stock badge, hint
   * and prune stay kind-specific), but the dirty/flush/close/title/sync-skip
   * and readOnly/onChange wiring all read it. */
  async function loadText(kind, name) {
    if (kind === 'generated') {
      const result = await window.forge.code.readGenerated(store.dir, name);
      if (!result.ok) throw new Error(result.error);
      return result.value;
    }
    if (kind === 'stock') return readStock(name);
    if (kind === 'user') return findFile('files', name)?.text ?? '';
    return findFile('overrides', name)?.text ?? (await readStock(name));
  }

  // ------------------------------------------------------------ committing

  /**
   * Write a tab's buffer into the project. An engine file becomes an override
   * the first time it differs from stock — and stops being one the moment it
   * matches again, so undoing an experiment by hand leaves no trace behind.
   */
  function commitTab(tab) {
    const text = tab.editor.getValue();
    if (text === tab.committed) return;
    const name = tab.name;

    if (tab.kind === 'user') {
      store.commit(`Edit ${name}`, (project) => {
        const file = project.code.files.find((entry) => entry.name === name);
        if (file) file.text = text;
      });
    } else {
      const stock = stockText.get(name);
      const matchesStock = stock !== undefined && text === stock;
      store.commit(matchesStock ? `Revert ${name}` : `Edit ${name}`, (project) => {
        const index = project.code.overrides.findIndex((entry) => entry.name === name);
        if (matchesStock) {
          if (index >= 0) project.code.overrides.splice(index, 1);
        } else if (index >= 0) {
          project.code.overrides[index].text = text;
        } else {
          project.code.overrides.push({ name, text });
          project.code.overrides.sort((a, b) => a.name.localeCompare(b.name));
        }
      });
    }
    tab.committed = text;
    renderTree();
    renderTabs();
    notePending();
  }

  /**
   * Each tab owns its own debounce timer, rather than one shared across the
   * Forge. With a shared timer, typing in one tab cancelled another tab's
   * pending commit before it ever fired -- masked by `flushPendingEdits()` on
   * save, but a real data-loss risk (e.g. a crash between two tabs' edits) and
   * the wrong shape once two tabs can be typed into side by side.
   */
  function scheduleCommit(tab) {
    clearTimeout(tab.pendingCommit);
    renderTabs(); // the dot appears as soon as the buffer differs
    // And so does the shell's. The commit is a moment away, but the close guard
    // lives in main and asks *now*: without this, typing and immediately hitting
    // the window's X closed it with no prompt and lost the edit.
    notePending();
    tab.pendingCommit = setTimeout(() => {
      tab.pendingCommit = null;
      commitTab(tab);
    }, COMMIT_DELAY);
  }

  /** Commit every open tab now — before a save, a tab switch, or leaving the Forge. */
  function flushPendingEdits() {
    // A snapshot, not the live array: a tab's own commitTab below can
    // synchronously prune an earlier-positioned stock tab through
    // onProjectChange (typing a copy back to exactly its stock text removes
    // the override, which store.commit() reports synchronously), which
    // shifts every later tab's index. A live-array for-of would have its
    // cursor already past the shifted-down position and skip the tab that
    // landed there -- exactly the tab a save right after this flush then
    // serializes stale. `onProjectChange` below uses this identical shape
    // for the identical reason. A tab already gone from `tabs` by the time
    // its own turn comes is skipped rather than committed again.
    for (const tab of [...tabs]) {
      if (isReference(tab)) continue;
      if (!tabs.includes(tab)) continue;
      clearTimeout(tab.pendingCommit);
      tab.pendingCommit = null;
      commitTab(tab);
    }
    notePending();
  }

  // ------------------------------------------------------------ tabs

  /**
   * Which pane a file being opened lands in. Split off from `openFile` because
   * both a tree click and the Build panel's error deep-link go through that one
   * function, and this item requires an explicit, stated rule rather than
   * "whichever pane happened to be focused last" by accident: the currently
   * focused pane, defaulting to the left/primary one -- which is also the only
   * answer this can ever give while there is no split, so single-pane behavior
   * is unchanged.
   */
  function pickTargetPane() {
    return splitKey && focusedPane === 'right' ? 'right' : 'left';
  }

  /**
   * The one place that makes `focusedPane` a fact rather than a claim: focus
   * whichever tab currently occupies `pane`, if any (a no-op while that pane
   * is empty, e.g. no split). Rounds 1 and 2 each patched a single bare
   * `focusedPane = ...` assignment with its own ad hoc focus call -- the real
   * defect was structural, not those two spots, since every write to
   * `focusedPane` needs one of these or the variable can lie. Every operation
   * below that changes what a pane shows, or which pane counts as "current",
   * ends with this -- after `renderPanes()`, since the target tab's DOM node
   * has to actually be mounted and visible before `.focus()` can do anything.
   *
   * This is also the one place the invariant behind all of that is enforced:
   * `focusedPane` may never name the split pane once `splitKey` is null. Round
   * 4's defect was a caller (`closeTab`'s primary-tab-collision branch)
   * nulling `splitKey` without remembering to also correct `focusedPane` --
   * the same shape rounds 1-3 each fixed at one call site apiece. Normalizing
   * here instead means a caller can pass a stale `'right'` and still end up
   * with a real, focused pane and a `focusedPane` that agrees with it,
   * whether or not it remembered to check `splitKey` itself first.
   */
  function focusPane(pane) {
    if (pane === 'right' && !splitKey) pane = 'left';
    focusedPane = pane;
    tabByKey(pane === 'right' ? splitKey : activeKey)?.editor.focus();
  }

  /**
   * Show `key` in `pane`, keeping the same tab from ever occupying both, and
   * finish by rendering and genuinely focusing wherever it ends up -- so a
   * caller can never reassign a pane without also focusing it.
   */
  function placeInPane(pane, key) {
    if (pane === 'right' && key === activeKey) {
      // Already visible on the left; showing it again on the right would
      // mean mounting one editor's single DOM node in two places at once.
      pane = 'left';
    } else if (pane === 'right') {
      splitKey = key;
    } else {
      if (splitKey === key) splitKey = null; // moving the split tab to the primary pane closes the split
      activeKey = key;
    }
    focusedPane = pane;
    renderPanes();
    focusPane(pane);
  }

  /**
   * Load-or-reuse a tab for (kind, name), never placing it in a pane -- that
   * is every caller's own decision, since a tree click, the Build panel's
   * deep link and `compareWithStock` each place differently. The single
   * point both `openFile` and `compareWithStock` go through, so the
   * dedup-in-flight and destroyed-Forge guards below cover every caller
   * rather than each reimplementing them (or forgetting to).
   *
   * Two callers racing the same not-yet-open (kind, name) -- two clicks
   * before the first's `loadText` resolves -- must produce exactly one tab.
   * The post-await recheck below (`already = tabByKey(key)`) already
   * guarantees that today, on its own, because nothing between `loadText`
   * resolving and the tab being pushed ever awaits again -- whichever
   * caller's load resolves first runs that whole tail to completion before
   * the other's continuation gets a turn. `pendingLoads` is what keeps a
   * *second caller from starting its own load at all*, sharing the first's
   * in-flight one instead: cheaper (one fetch, not two, for the same file),
   * and the one thing that stays correct if that tail ever grows a second
   * `await` of its own, at which point the recheck's guarantee would quietly
   * stop holding. Set synchronously, before this function's own first
   * `await`, so a second call arriving on the same synchronous tick (e.g.
   * two `button.click()`s back to back) already sees it.
   */
  async function ensureTab(kind, name) {
    const key = tabKey(kind, name);
    const existing = tabByKey(key);
    if (existing) return existing;

    const inFlight = pendingLoads.get(key);
    if (inFlight) return inFlight;

    const promise = (async () => {
      let text;
      try {
        text = await loadText(kind, name);
      } catch (error) {
        toast(error.message, 'error');
        return null;
      }
      // The Forge may have been torn down while that load was in flight --
      // nothing left to push this tab into.
      if (destroyed) return null;
      // Belt-and-braces: `pendingLoads` already stops two `ensureTab` calls
      // for this same key from each starting their own load, but this is the
      // one place that actually creates a tab, so it re-checks rather than
      // trusting that no other path could have.
      const already = tabByKey(key);
      if (already) return already;

      const referenceKind = kind in REFERENCE_LABELS;
      const tab = { kind, name, committed: text, editor: null, pendingCommit: null };
      tab.editor = createEditor({
        value: text,
        readOnly: referenceKind,
        // Never committed, never dirty -- a reference tab's onChange is a
        // no-op even though its DOM textarea is also readOnly, so reaching
        // its editor through anything other than the keyboard still can't
        // wire an edit back into commitTab under this file's own name.
        onChange: referenceKind ? () => {} : () => scheduleCommit(tab)
      });
      tabs.push(tab);
      // Every creation path renders, structurally, here -- not once per
      // caller that happens to remember to. A tab this pushes can otherwise
      // go unrendered two ways: a superseded compare that leaves it parked
      // (nothing else in that branch touches the DOM), or a stock load that
      // fails *after* the engine copy was already created (the caller
      // returns immediately on `null`, past any placement). One call here
      // covers both, and any caller that goes on to place the tab still
      // gets a second, cheap re-render on top of it.
      renderTabs();
      return tab;
    })();

    pendingLoads.set(key, promise);
    try {
      return await promise;
    } finally {
      pendingLoads.delete(key);
    }
  }

  async function openFile(kind, name, line = 0) {
    const key = tabKey(kind, name);
    const tab = await ensureTab(kind, name);
    if (!tab || destroyed) return null;
    // Evaluated fresh, after the await -- not a snapshot taken before it --
    // so two racing opens of the same file each place correctly: whichever
    // continuation runs second sees the first's placement already landed and
    // only re-renders, instead of placing the same tab into a pane twice.
    if (key !== activeKey && key !== splitKey) placeInPane(pickTargetPane(), key);
    else renderPanes();
    if (line) tab.editor.gotoLine(line); // gotoLine focuses an editable editor itself
    // Unconditional, not just under `if (line)`: a plain reopen (line 0) of a
    // tab that still carries an earlier deep link's marker has to clear it,
    // the same way the pre-`ensureTab` code always called this on its
    // existing-tab branch. gotoLine stays guarded -- markLine(0) means
    // "clear", but gotoLine(0) resolves to line 1 and would steal focus.
    tab.editor.markLine(line);
    return tab;
  }

  /** Put `tab` into the split pane, or close the split if it is already there. */
  function toggleSplit(tab) {
    const key = tabKey(tab.kind, tab.name);
    if (splitKey === key) {
      splitKey = null; // focusPane() below normalizes focusedPane off 'right' once splitKey is gone
    } else if (key !== activeKey) {
      splitKey = key;
      focusedPane = 'right';
    } else {
      return; // nothing to do -- the tab strip hides this button for that case anyway
    }
    renderPanes();
    focusPane(focusedPane);
  }

  /**
   * `commit: false` throws the buffer away instead of writing it back — for the
   * tabs whose file is being removed, where committing would recreate it.
   */
  function closeTab(tab, { commit = true } = {}) {
    const key = tabKey(tab.kind, tab.name);
    // Already closed -- two same-file compares sharing one stock load can
    // each decide the shared original needs closing, and the second must be
    // a no-op rather than `splice(-1, 1)`, which would remove the *last*
    // tab in the strip instead of doing nothing.
    if (!tabs.includes(tab)) return;
    clearTimeout(tab.pendingCommit);
    if (commit && !isReference(tab)) commitTab(tab);
    // Taken *after* the commit above, not before: typing the copy back to
    // exactly its stock text makes commitTab's own store.commit() remove the
    // override, which onProjectChange responds to synchronously by pruning
    // this file's own stock/original tab if one sits earlier in `tabs` --
    // shifting every index after it. Recomputing here rather than reusing a
    // pre-commit index is what a shift like that needs. This `< 0` check is
    // not the earlier double-close guard again -- it is that same shift
    // carried to its extreme, the commit having moved (or, in principle,
    // already closed) this very tab.
    const index = tabs.indexOf(tab);
    if (index < 0) return;
    tabs.splice(index, 1);
    tab.editor.destroy();
    if (splitKey === key) {
      splitKey = null; // focusPane() below normalizes focusedPane off 'right' once splitKey is gone
    }
    if (activeKey === key) {
      const next = tabs[index] ?? tabs[index - 1] ?? null;
      activeKey = next ? tabKey(next.kind, next.name) : null;
      // The auto-picked next tab may already be showing in the split pane --
      // showing it on the left too would mount its one editor node twice.
      if (activeKey !== null && activeKey === splitKey) splitKey = null;
    }
    renderPanes();
    // Whatever a closed tab leaves behind -- the pane that already survived
    // untouched, or the neighbor that just took over its slot -- is what
    // there is to look at now, so it is the one reasonable thing to focus.
    // Also closes the loop this round exists for: no operation that changes a
    // pane's assignment may skip the real focus that backs it.
    focusPane(focusedPane);
    notePending();
  }

  /** Put the project's copy of a file back into the tab showing it. */
  function syncTab(tab, text) {
    if (text === tab.committed) return;
    tab.editor.setValue(text);
    tab.committed = text;
  }

  function hintKindFor(tab) {
    return tab.kind === 'generated'
      ? 'generated'
      : tab.kind === 'stock'
        ? 'original'
        : tab.kind === 'user'
          ? 'user'
          : findFile('overrides', tab.name)
            ? 'override'
            : 'stock';
  }

  const placeholder = () =>
    el(
      'div.placeholder',
      null,
      el('div.placeholder-glyph', null, '‹›'),
      el('h2', null, 'The code behind your game'),
      el(
        'p',
        null,
        'Pick a file on the left. Engine files are the app’s own 6502 source — editing one keeps ' +
          'your changes in this project, so the original is always there to go back to.'
      )
    );

  /** Render one pane's hint strip and editor host for whichever tab `key` names. */
  function renderPane(hintNode, hostNode, key, { showPlaceholder = false } = {}) {
    const tab = key ? tabByKey(key) : null;
    if (!tab) {
      fill(hintNode);
      hintNode.hidden = true;
      fill(hostNode, showPlaceholder ? placeholder() : null);
      return;
    }
    hintNode.hidden = false;
    fill(hintNode, HINTS[hintKindFor(tab)]);
    // Only when it actually changes. Removing and re-appending a node blurs
    // whatever inside it had focus, and this runs on every commit — including the
    // debounced one a few hundred milliseconds into typing, which would take the
    // caret away mid-sentence.
    if (hostNode.firstChild !== tab.editor.el) fill(hostNode, tab.editor.el);
  }

  /** Render both panes -- the primary (left) one always, the split (right) one only while active. */
  function renderPanes() {
    renderTabs();
    renderTree();
    renderPane(leftHint, leftHost, activeKey, { showPlaceholder: true });
    rightPane.hidden = !splitKey;
    divider.hidden = !splitKey;
    applySplitRatio();
    if (splitKey) renderPane(rightHint, rightHost, splitKey);
  }

  function renderTabs() {
    fill(
      tabsHost,
      tabs.length
        ? tabs.map((tab) => {
            const key = tabKey(tab.kind, tab.name);
            const dirty = tabDirty(tab);
            return el(
              'div.tab.code-tab',
              {
                class: key === activeKey ? 'active' : key === splitKey ? 'active-split' : '',
                title: REFERENCE_LABELS[tab.kind] ? `${tab.name} (${REFERENCE_LABELS[tab.kind]})` : tab.name,
                onclick: () => {
                  // Already showing in one of the two panes: nothing to do --
                  // unlike the split-toggle button below, a plain click never
                  // reassigns which pane an already-visible tab occupies.
                  if (key === activeKey || key === splitKey) return;
                  flushPendingEdits();
                  placeInPane('left', key);
                }
              },
              el('span.code-tab-name', null, tab.name.replace(/^assets\//, '')),
              tab.kind === 'stock' ? el('span.code-tab-kind', null, 'original') : null,
              dirty ? el('span.code-tab-dot') : null,
              // Not for the primary (left) pane's own tab: there is nothing to
              // open into the split for a tab that is already showing there,
              // and toggleSplit() would silently no-op on it.
              tabs.length > 1 && key !== activeKey
                ? el(
                    'button.code-tab-split',
                    {
                      class: key === splitKey ? 'active' : '',
                      title: key === splitKey ? 'Close split pane' : 'Open in split pane',
                      onclick: (event) => {
                        event.stopPropagation();
                        toggleSplit(tab);
                      }
                    },
                    '⧉'
                  )
                : null,
              el(
                'button.code-tab-close',
                {
                  title: 'Close',
                  onclick: (event) => {
                    event.stopPropagation();
                    closeTab(tab);
                  }
                },
                '×'
              )
            );
          })
        : el('div.code-tabs-empty', null, 'No file open')
    );
  }

  // ------------------------------------------------------------ the tree

  function treeRow(kind, name, { badge = null, actions = [], label = name } = {}) {
    const key = tabKey(kind, name);
    return el(
      'div.tree-row',
      { class: key === activeKey ? 'active' : '', onclick: () => openFile(kind, name) },
      el('span.tree-name', { title: name }, label),
      badge ? el('span.tree-badge', null, badge) : null,
      actions.map((action) =>
        el(
          'button.tree-action',
          {
            title: action.title,
            onclick: (event) => {
              event.stopPropagation();
              action.run();
            }
          },
          action.glyph
        )
      )
    );
  }

  /**
   * Show `name`'s override beside the engine's own original: the copy in the
   * left (editable) pane, the read-only original in the right, regardless of
   * where either tab was before. Unlike a fresh open, this is a two-pane
   * operation with a stated layout, so it never consults `pickTargetPane()` --
   * placing the copy left first (closing the split if it was the split tab)
   * and the original right second is what makes that layout land the same way
   * from all four prior states (neither open, only the copy open in either
   * pane, the copy open and the original parked, or both open swapped).
   *
   * Ensure first, place last. Both `ensureTab`s run to completion *before*
   * either tab is placed anywhere -- round 1 placed the copy left right
   * after its own await and only the original after the second, which round
   * 2's review caught: a tab-strip click during the stock fetch could move
   * the copy to a different pane (or park it), and completion then placed
   * only the original beside whatever the click had left on the left,
   * mismatching the pair. Placing nothing until one final synchronous block
   * -- after the *last* await -- means an intervening pane change is simply
   * overwritten by this compare's own placement when it does land, the same
   * way it always overwrote a start state before this fix, instead of being
   * built on top of.
   *
   * `compareSeq` is the other half: two compares (any two files, including
   * the same one twice) racing each other must leave the panes showing the
   * *last-clicked* pair, never a mix of two. Taken at entry, compared after
   * the last await -- a superseded compare's own tabs stay exactly as
   * `ensureTab` left them (open, parked, available from the tree again --
   * and rendered there already, since `ensureTab` itself renders whatever it
   * creates) rather than being placed over the newer compare's own result.
   *
   * The six checks below run in this order because *order is the fix*
   * (round 3 review): two compares for the *same* file share one in-flight
   * stock load through `pendingLoads`, so an older call whose own copy got
   * closed mid-fetch and a newer call that reopened the same file both
   * resume off that one shared promise. Checking "is my copy still open"
   * before "am I still the latest" let the older call close the shared
   * original out from under the newer one before the newer call ever got a
   * chance to say it still needed it -- the newer call would then place a
   * stock key that no longer names a tab. Override-gone is checked first and
   * unconditionally instead, because it means the same thing for every
   * same-file compare alike (there is nothing left to compare against, full
   * stop) -- any of them may prune the stale original, and whichever gets
   * there first is fine. Supersession is checked *before* the copy-closed
   * check that follows it, so only the single latest compare for this file
   * ever reaches that line -- it cannot strand a compare newer than itself,
   * because there isn't one.
   */
  async function compareWithStock(name) {
    const seq = ++compareSeq;

    const engineKey = tabKey('engine', name);
    const engineTab = await ensureTab('engine', name);
    if (!engineTab) return;

    const stockKey = tabKey('stock', name);
    const stockTab = await ensureTab('stock', name);
    if (!stockTab) return;

    // Everything from here on is one synchronous block: no placement happens
    // until every guard below has passed, so this compare's two tabs always
    // land together or not at all -- never a placement built on a stale
    // assumption about where either tab already was.
    if (destroyed) return;

    if (!findFile('overrides', name)) {
      // Nothing left to compare against, for every same-file compare alike
      // -- the override was reverted or undone. The original has no reason
      // to exist any more; whichever compare notices first prunes it.
      if (tabs.includes(stockTab)) closeTab(stockTab, { commit: false });
      return;
    }
    if (seq !== compareSeq) {
      // A later compare -- this file clicked again, or a different one --
      // started since and owns placing the panes now. This compare's own
      // override is still live, so both its tabs are left exactly as
      // `ensureTab` returned them: open, rendered, reachable again from the
      // tree's own ◫/tab strip. Checked before the copy-closed guard below
      // on purpose: only the single latest compare for this file ever
      // reaches that line, so it can never close a tab a newer compare is
      // still counting on.
      return;
    }
    if (!tabs.includes(engineTab)) {
      // The copy itself was closed while this (the latest) compare's own
      // fetch was in flight -- nothing to show it beside. Only reachable by
      // the latest compare, so this can never strand one that supersedes it.
      if (tabs.includes(stockTab)) closeTab(stockTab, { commit: false });
      return;
    }
    if (!tabs.includes(stockTab)) {
      // An earlier same-file compare, sharing this stock load, already
      // closed it (its own copy was gone, or the override was) before this
      // compare reached its own checks above. Nothing left to place.
      return;
    }
    placeInPane('left', engineKey);
    placeInPane('right', stockKey);
    // The compare view is for looking, not typing in the original -- leave
    // focus in the editable copy on the left.
    focusPane('left');
  }

  async function revert(name) {
    const confirmed = await confirmModal(
      `Revert ${name}?`,
      'Your changes to this file are discarded and the engine’s original is used again. This can be undone.',
      'Revert'
    );
    if (!confirmed) return;
    // Drop the buffer first, or the open tab's next commit writes the override
    // straight back.
    const tab = tabs.find((entry) => entry.kind === 'engine' && entry.name === name);
    store.commit(`Revert ${name}`, (project) => {
      const index = project.code.overrides.findIndex((entry) => entry.name === name);
      if (index >= 0) project.code.overrides.splice(index, 1);
    });
    if (tab) {
      const stock = await readStock(name);
      tab.editor.setValue(stock);
      tab.committed = stock;
    }
    renderPanes();
    toast(`${name} is back to the original.`, 'info');
  }

  async function newFile() {
    // The engine list decides whether a name collides with a stock file, and it
    // arrives asynchronously.
    await engineReady;
    if (codeSlice().files.length >= CODE_LIMITS.files) {
      return toast(
        `A project can hold ${CODE_LIMITS.files} of your own code files, and this one is full. ` +
          'Delete one first.',
        'error'
      );
    }
    const name = await promptModal(
      'New code file',
      'File name — letters, numbers, dashes and underscores, ending in .asm',
      '',
      'Create'
    );
    if (!name) return;
    if (!CODE_FILE_RE.test(name)) {
      return toast('That name needs to end in .asm and contain no slashes.', 'error');
    }
    if (engineFiles.some((file) => file.name === name)) {
      return toast(`${name} is an engine file. Pick another name, or edit that file directly.`, 'error');
    }
    if (findFile('files', name)) return toast(`${name} already exists.`, 'error');

    const text =
      `; ${name} -- your own code, assembled into the fixed bank at $C000.\n` +
      '; Call a label in here from any engine file you have edited:  jsr my_routine\n' +
      '\n' +
      'my_routine:\n' +
      '  rts\n';
    store.commit(`Create ${name}`, (project) => {
      project.code.files.push({ name, text });
      project.code.files.sort((a, b) => a.name.localeCompare(b.name));
    });
    await openFile('user', name);
    renderTree();
  }

  async function deleteFile(name) {
    const confirmed = await confirmModal(
      `Delete ${name}?`,
      'The file is removed from this project. This can be undone.',
      'Delete'
    );
    if (!confirmed) return;
    // Closing normally commits, which would recreate what we are about to delete.
    const tab = tabs.find((entry) => entry.kind === 'user' && entry.name === name);
    if (tab) closeTab(tab, { commit: false });
    store.commit(`Delete ${name}`, (project) => {
      const index = project.code.files.findIndex((entry) => entry.name === name);
      if (index >= 0) project.code.files.splice(index, 1);
    });
    renderTree();
    renderPanes();
  }

  async function refreshGenerated() {
    if (!store.dir) return;
    const result = await window.forge.code.generatedFiles(store.dir);
    generatedFiles = result.ok ? result.value : [];
    renderTree();
  }

  function renderTree() {
    const { overrides, files } = codeSlice();
    const overridden = new Set(overrides.map((file) => file.name));

    fill(
      treeHost,
      el(
        'div.tree-group',
        null,
        el('div.tree-head', null, el('span', null, 'Engine'), el('span.tree-count', null, String(engineFiles.length))),
        engineFiles.map((file) =>
          treeRow('engine', file.name, {
            badge: overridden.has(file.name) ? 'edited' : null,
            actions: overridden.has(file.name)
              ? [
                  {
                    glyph: '◫',
                    title: 'Show the original beside your copy',
                    run: () => compareWithStock(file.name)
                  },
                  { glyph: '↺', title: `Revert ${file.name} to the original`, run: () => revert(file.name) }
                ]
              : []
          })
        )
      ),
      el(
        'div.tree-group',
        null,
        el(
          'div.tree-head',
          null,
          el('span', null, 'Your files'),
          el('button.tree-add', { title: 'New code file', onclick: newFile }, '+')
        ),
        files.length
          ? files.map((file) =>
              treeRow('user', file.name, {
                actions: [{ glyph: '×', title: `Delete ${file.name}`, run: () => deleteFile(file.name) }]
              })
            )
          : el('div.tree-empty', null, 'None yet. Add one with +.')
      ),
      el(
        'div.tree-group',
        null,
        el(
          'div.tree-head',
          null,
          el('span', null, 'Generated'),
          el('button.tree-add', { title: 'Refresh', onclick: refreshGenerated }, '⟳')
        ),
        generatedFiles.length
          ? generatedFiles.map((name) =>
              treeRow('generated', name, { label: name.replace(/^assets\//, '') })
            )
          : el('div.tree-empty', null, 'Build the project to see what it generates.')
      )
    );
  }

  // ------------------------------------------------------------ shell

  const root = el(
    'div.forge',
    { style: { gridTemplateColumns: '240px 1fr' } },
    el('div.panel', null, el('div.panel-head', null, 'Files'), el('div.panel-body.tree-body', null, treeHost)),
    el(
      'div.panel',
      null,
      el('div.panel-head.code-head', null, tabsHost),
      el('div.panel-body.code-body', null, panesHost)
    )
  );

  container.append(root);
  renderTree();
  renderPanes();
  app.setMeta('Code Forge');

  // Kept, not just fired: anything that has to *know* whether a name is a stock
  // engine file — the new-file check, and the build panel's deep link into an
  // error — has to wait for it. A deep link arrives the moment this Forge mounts,
  // which is exactly when the list is still empty.
  const engineReady = window.forge.code.engineFiles().then((result) => {
    if (result.ok) engineFiles = result.value;
    renderTree();
  });
  refreshGenerated();

  return {
    destroy() {
      destroyed = true;
      stopWindowDragListeners();
      flushPendingEdits();
      for (const tab of tabs) tab.editor.destroy();
      app.setMeta('');
    },
    flushPendingEdits,
    hasPendingEdits: () => tabs.some(tabDirty),
    onProjectChange() {
      // An undo, a redo, or an edit from somewhere else. Re-read every open tab
      // from the project — except one whose buffer is mid-edit and already
      // matches what was committed, which is the tab that caused this.
      for (const tab of [...tabs]) {
        if (tab.kind === 'stock') {
          // A stock tab exists only while its override does -- this one place
          // covers the revert action, an undo that removes the override, and
          // typing the copy back to stock (commitTab's own Revert branch),
          // since store.commit() and store.undo()/redo() all route here (see
          // app.js's store.subscribe).
          if (!findFile('overrides', tab.name)) closeTab(tab, { commit: false });
          continue;
        }
        // Every other reference kind (today, only 'generated') has nothing to
        // sync against a project field -- skip by default rather than
        // falling into the engine override sync below, so a future read-only
        // kind added to REFERENCE_LABELS with no branch of its own here is
        // left alone instead of silently having its reference text replaced.
        if (isReference(tab)) continue;

        if (tab.kind === 'user') {
          const file = findFile('files', tab.name);
          // Nothing behind the tab any more — an undone Create, or a Delete from
          // elsewhere. Left open it stays editable, and every later commit looks
          // for a file that is not there and drops the edit on the floor.
          if (!file) closeTab(tab, { commit: false });
          else syncTab(tab, file.text);
          continue;
        }

        const override = findFile('overrides', tab.name);
        if (override) {
          syncTab(tab, override.text);
          continue;
        }
        // No override left, so the tab shows the stock file again. It may never
        // have been fetched — a tab opened on an already-overridden file reads
        // the override and never touches the original — so fetch it before
        // deciding, rather than leaving the edit on screen as if it survived.
        const stock = stockText.get(tab.name);
        if (stock !== undefined) {
          syncTab(tab, stock);
          continue;
        }
        readStock(tab.name).then(
          (text) => {
            // The project may have moved on again while that was in flight.
            if (!tabs.includes(tab) || findFile('overrides', tab.name)) return;
            syncTab(tab, text);
            renderTabs();
          },
          () => {}
        );
      }
      renderPanes();
      notePending();
    },
    /**
     * Open a file the build reported an error in. Names arrive as the assembler
     * saw them, relative to the build folder — which is why overrides are written
     * there under their own names and with their own line numbers.
     */
    async openFile(name, line = 0) {
      await engineReady;
      const bare = name.replace(/^.*[/\\]/, '');
      if (name.startsWith('assets/') || bare.endsWith('.inc')) {
        await refreshGenerated();
        const match = generatedFiles.find((file) => file === name || file.endsWith(`/${bare}`));
        if (match) return openFile('generated', match, line);
      }
      if (engineFiles.some((file) => file.name === bare)) return openFile('engine', bare, line);
      if (findFile('files', bare)) return openFile('user', bare, line);
      toast(`${name} is not a file the Code Forge can open.`, 'warn');
      return null;
    }
  };
}
