// Code Forge: the escape hatch. Every source file that goes into the ROM, in a
// tree on the left and tabbed editors on the right.
//
// Three kinds of file, and the difference between them is the whole design:
//
//  - **Engine** files are the app's own 6502 sources. Editing one does not touch
//    them: the edit is saved into the *project* as an override, and the build
//    lays it over the stock copy. So one project's custom code cannot leak into
//    another, and reverting is deleting the copy.
//  - **Your files** are new sources the project owns outright. The generator
//    lists them in assets/usercode.inc, which engine/main.asm includes in the
//    fixed kernel — so a label defined here can be called from anywhere.
//  - **Generated** files are the build's own output, read-only because the next
//    build deletes and rewrites the whole folder.
//
// Edits live in `store.project.code`, which is what gives them undo, the dirty
// dot and saving without inventing a second version of any of it. A code editor
// never blurs, so instead of committing per keystroke (an unusable undo stack)
// or on blur (a commit that may never come), typing commits once it pauses.

import { store } from '../../store.js';
import { el, fill, toast, confirmModal, promptModal } from '../../ui.js';
import { CODE_FILE_RE, CODE_LIMITS } from '../../../shared/project.js';
import { createEditor } from './editor.js';

/** How long typing has to pause before it becomes one undo entry. */
const COMMIT_DELAY = 600;

const HINTS = {
  stock:
    'Editing this makes a copy inside your project. The app’s own engine is left alone, and you can ' +
    'revert to the original at any time.',
  override: 'Your project’s copy of this engine file. The build uses this instead of the original.',
  user:
    'Your own code, assembled into the fixed bank at $C000. Call a label in here with jsr from any ' +
    'engine file you have edited.',
  generated: 'Generated by the build from your project. Read-only — the next build rewrites it.'
};

export function mount(container, app) {
  // Stock engine sources, fetched once each and kept for the session: they are
  // read-only inputs that cannot change while the app runs, and comparing
  // against them is how an override knows whether it still differs.
  const stockText = new Map();
  let engineFiles = [];
  let generatedFiles = [];

  /** Open tabs, in strip order. */
  const tabs = [];
  // `activeKey` is the primary (left) pane's tab; `splitKey` is the second
  // (right) pane's, or null when the Forge shows a single editor -- which is
  // the only state before this item and must keep behaving exactly as before.
  let activeKey = null;
  let splitKey = null;
  // Which pane a fresh open (a tree click, or the Build panel's error deep
  // link) lands in: whichever pane's textarea last held focus. Defaults to
  // 'left' and is only ever read as 'right' while a split is actually showing
  // (see pickTargetPane), so single-pane behavior never depends on this.
  let focusedPane = 'left';

  const treeHost = el('div.code-tree');
  const tabsHost = el('div.tabs.code-tabs');
  const leftHint = el('div.code-hint');
  const leftHost = el('div.code-host');
  const rightHint = el('div.code-hint');
  const rightHost = el('div.code-host');
  const leftPane = el('div.code-pane', null, leftHint, leftHost);
  const rightPane = el('div.code-pane', { hidden: true }, rightHint, rightHost);
  const panesHost = el('div.code-panes', null, leftPane, rightPane);

  leftHost.addEventListener('focusin', () => {
    focusedPane = 'left';
  });
  rightHost.addEventListener('focusin', () => {
    focusedPane = 'right';
  });

  const codeSlice = () => store.project?.code ?? { overrides: [], files: [] };
  const findFile = (group, name) => codeSlice()[group].find((file) => file.name === name) ?? null;
  const tabKey = (kind, name) => `${kind}:${name}`;
  const tabByKey = (key) => tabs.find((tab) => tabKey(tab.kind, tab.name) === key) ?? null;
  const activeTab = () => tabByKey(activeKey);

  // A buffer that has diverged from what is committed is the tab strip's dot and
  // the shell's unsaved work — one predicate, so the dot and the close guard
  // cannot disagree about whether typing is at risk.
  const tabDirty = (tab) => tab.kind !== 'generated' && tab.editor.getValue() !== tab.committed;
  const notePending = () => app.notePendingEdits?.();

  // ------------------------------------------------------------ file access

  async function readStock(name) {
    if (stockText.has(name)) return stockText.get(name);
    const response = await fetch(`forge://app/engine/${name}`);
    if (!response.ok) throw new Error(`Could not read the engine's ${name}.`);
    const text = await response.text();
    stockText.set(name, text);
    return text;
  }

  /** The text a tab should show, and whether the user may edit it. */
  async function loadText(kind, name) {
    if (kind === 'generated') {
      const result = await window.forge.code.readGenerated(store.dir, name);
      if (!result.ok) throw new Error(result.error);
      return result.value;
    }
    if (kind === 'user') return findFile('files', name)?.text ?? '';
    return findFile('overrides', name)?.text ?? (await readStock(name));
  }

  // ------------------------------------------------------------ committing

  /**
   * Write a tab's buffer into the project. An engine file becomes an override
   * the first time it differs from stock — and stops being one the moment it
   * matches again, so undoing an experiment by hand leaves no trace behind.
   */
  function commitTab(tab) {
    const text = tab.editor.getValue();
    if (text === tab.committed) return;
    const name = tab.name;

    if (tab.kind === 'user') {
      store.commit(`Edit ${name}`, (project) => {
        const file = project.code.files.find((entry) => entry.name === name);
        if (file) file.text = text;
      });
    } else {
      const stock = stockText.get(name);
      const matchesStock = stock !== undefined && text === stock;
      store.commit(matchesStock ? `Revert ${name}` : `Edit ${name}`, (project) => {
        const index = project.code.overrides.findIndex((entry) => entry.name === name);
        if (matchesStock) {
          if (index >= 0) project.code.overrides.splice(index, 1);
        } else if (index >= 0) {
          project.code.overrides[index].text = text;
        } else {
          project.code.overrides.push({ name, text });
          project.code.overrides.sort((a, b) => a.name.localeCompare(b.name));
        }
      });
    }
    tab.committed = text;
    renderTree();
    renderTabs();
    notePending();
  }

  /**
   * Each tab owns its own debounce timer, rather than one shared across the
   * Forge. With a shared timer, typing in one tab cancelled another tab's
   * pending commit before it ever fired -- masked by `flushPendingEdits()` on
   * save, but a real data-loss risk (e.g. a crash between two tabs' edits) and
   * the wrong shape once two tabs can be typed into side by side.
   */
  function scheduleCommit(tab) {
    clearTimeout(tab.pendingCommit);
    renderTabs(); // the dot appears as soon as the buffer differs
    // And so does the shell's. The commit is a moment away, but the close guard
    // lives in main and asks *now*: without this, typing and immediately hitting
    // the window's X closed it with no prompt and lost the edit.
    notePending();
    tab.pendingCommit = setTimeout(() => {
      tab.pendingCommit = null;
      commitTab(tab);
    }, COMMIT_DELAY);
  }

  /** Commit every open tab now — before a save, a tab switch, or leaving the Forge. */
  function flushPendingEdits() {
    for (const tab of tabs) {
      if (tab.kind === 'generated') continue;
      clearTimeout(tab.pendingCommit);
      tab.pendingCommit = null;
      commitTab(tab);
    }
    notePending();
  }

  // ------------------------------------------------------------ tabs

  /**
   * Which pane a file being opened lands in. Split off from `openFile` because
   * both a tree click and the Build panel's error deep-link go through that one
   * function, and this item requires an explicit, stated rule rather than
   * "whichever pane happened to be focused last" by accident: the currently
   * focused pane, defaulting to the left/primary one -- which is also the only
   * answer this can ever give while there is no split, so single-pane behavior
   * is unchanged.
   */
  function pickTargetPane() {
    return splitKey && focusedPane === 'right' ? 'right' : 'left';
  }

  /**
   * The one place that makes `focusedPane` a fact rather than a claim: focus
   * whichever tab currently occupies `pane`, if any (a no-op while that pane
   * is empty, e.g. no split). Rounds 1 and 2 each patched a single bare
   * `focusedPane = ...` assignment with its own ad hoc focus call -- the real
   * defect was structural, not those two spots, since every write to
   * `focusedPane` needs one of these or the variable can lie. Every operation
   * below that changes what a pane shows, or which pane counts as "current",
   * ends with this -- after `renderPanes()`, since the target tab's DOM node
   * has to actually be mounted and visible before `.focus()` can do anything.
   *
   * This is also the one place the invariant behind all of that is enforced:
   * `focusedPane` may never name the split pane once `splitKey` is null. Round
   * 4's defect was a caller (`closeTab`'s primary-tab-collision branch)
   * nulling `splitKey` without remembering to also correct `focusedPane` --
   * the same shape rounds 1-3 each fixed at one call site apiece. Normalizing
   * here instead means a caller can pass a stale `'right'` and still end up
   * with a real, focused pane and a `focusedPane` that agrees with it,
   * whether or not it remembered to check `splitKey` itself first.
   */
  function focusPane(pane) {
    if (pane === 'right' && !splitKey) pane = 'left';
    focusedPane = pane;
    tabByKey(pane === 'right' ? splitKey : activeKey)?.editor.focus();
  }

  /**
   * Show `key` in `pane`, keeping the same tab from ever occupying both, and
   * finish by rendering and genuinely focusing wherever it ends up -- so a
   * caller can never reassign a pane without also focusing it.
   */
  function placeInPane(pane, key) {
    if (pane === 'right' && key === activeKey) {
      // Already visible on the left; showing it again on the right would
      // mean mounting one editor's single DOM node in two places at once.
      pane = 'left';
    } else if (pane === 'right') {
      splitKey = key;
    } else {
      if (splitKey === key) splitKey = null; // moving the split tab to the primary pane closes the split
      activeKey = key;
    }
    focusedPane = pane;
    renderPanes();
    focusPane(pane);
  }

  async function openFile(kind, name, line = 0) {
    const key = tabKey(kind, name);
    const existing = tabByKey(key);
    if (existing) {
      if (key !== activeKey && key !== splitKey) placeInPane(pickTargetPane(), key);
      else renderPanes();
      if (line) existing.editor.gotoLine(line); // gotoLine focuses an editable editor itself
      existing.editor.markLine(line);
      return existing;
    }

    let text;
    try {
      text = await loadText(kind, name);
    } catch (error) {
      toast(error.message, 'error');
      return null;
    }

    const tab = { kind, name, committed: text, editor: null, pendingCommit: null };
    tab.editor = createEditor({
      value: text,
      readOnly: kind === 'generated',
      onChange: () => scheduleCommit(tab)
    });
    tabs.push(tab);
    placeInPane(pickTargetPane(), key);
    if (line) {
      tab.editor.gotoLine(line);
      tab.editor.markLine(line);
    }
    return tab;
  }

  /** Put `tab` into the split pane, or close the split if it is already there. */
  function toggleSplit(tab) {
    const key = tabKey(tab.kind, tab.name);
    if (splitKey === key) {
      splitKey = null; // focusPane() below normalizes focusedPane off 'right' once splitKey is gone
    } else if (key !== activeKey) {
      splitKey = key;
      focusedPane = 'right';
    } else {
      return; // nothing to do -- the tab strip hides this button for that case anyway
    }
    renderPanes();
    focusPane(focusedPane);
  }

  /**
   * `commit: false` throws the buffer away instead of writing it back — for the
   * tabs whose file is being removed, where committing would recreate it.
   */
  function closeTab(tab, { commit = true } = {}) {
    clearTimeout(tab.pendingCommit);
    if (commit && tab.kind !== 'generated') commitTab(tab);
    const key = tabKey(tab.kind, tab.name);
    const index = tabs.indexOf(tab);
    tabs.splice(index, 1);
    tab.editor.destroy();
    if (splitKey === key) {
      splitKey = null; // focusPane() below normalizes focusedPane off 'right' once splitKey is gone
    }
    if (activeKey === key) {
      const next = tabs[index] ?? tabs[index - 1] ?? null;
      activeKey = next ? tabKey(next.kind, next.name) : null;
      // The auto-picked next tab may already be showing in the split pane --
      // showing it on the left too would mount its one editor node twice.
      if (activeKey !== null && activeKey === splitKey) splitKey = null;
    }
    renderPanes();
    // Whatever a closed tab leaves behind -- the pane that already survived
    // untouched, or the neighbor that just took over its slot -- is what
    // there is to look at now, so it is the one reasonable thing to focus.
    // Also closes the loop this round exists for: no operation that changes a
    // pane's assignment may skip the real focus that backs it.
    focusPane(focusedPane);
    notePending();
  }

  /** Put the project's copy of a file back into the tab showing it. */
  function syncTab(tab, text) {
    if (text === tab.committed) return;
    tab.editor.setValue(text);
    tab.committed = text;
  }

  function hintKindFor(tab) {
    return tab.kind === 'generated'
      ? 'generated'
      : tab.kind === 'user'
        ? 'user'
        : findFile('overrides', tab.name)
          ? 'override'
          : 'stock';
  }

  const placeholder = () =>
    el(
      'div.placeholder',
      null,
      el('div.placeholder-glyph', null, '‹›'),
      el('h2', null, 'The code behind your game'),
      el(
        'p',
        null,
        'Pick a file on the left. Engine files are the app’s own 6502 source — editing one keeps ' +
          'your changes in this project, so the original is always there to go back to.'
      )
    );

  /** Render one pane's hint strip and editor host for whichever tab `key` names. */
  function renderPane(hintNode, hostNode, key, { showPlaceholder = false } = {}) {
    const tab = key ? tabByKey(key) : null;
    if (!tab) {
      fill(hintNode);
      hintNode.hidden = true;
      fill(hostNode, showPlaceholder ? placeholder() : null);
      return;
    }
    hintNode.hidden = false;
    fill(hintNode, HINTS[hintKindFor(tab)]);
    // Only when it actually changes. Removing and re-appending a node blurs
    // whatever inside it had focus, and this runs on every commit — including the
    // debounced one a few hundred milliseconds into typing, which would take the
    // caret away mid-sentence.
    if (hostNode.firstChild !== tab.editor.el) fill(hostNode, tab.editor.el);
  }

  /** Render both panes -- the primary (left) one always, the split (right) one only while active. */
  function renderPanes() {
    renderTabs();
    renderTree();
    renderPane(leftHint, leftHost, activeKey, { showPlaceholder: true });
    rightPane.hidden = !splitKey;
    if (splitKey) renderPane(rightHint, rightHost, splitKey);
  }

  function renderTabs() {
    fill(
      tabsHost,
      tabs.length
        ? tabs.map((tab) => {
            const key = tabKey(tab.kind, tab.name);
            const dirty = tabDirty(tab);
            return el(
              'div.tab.code-tab',
              {
                class: key === activeKey ? 'active' : key === splitKey ? 'active-split' : '',
                title: tab.kind === 'generated' ? `${tab.name} (generated)` : tab.name,
                onclick: () => {
                  // Already showing in one of the two panes: nothing to do --
                  // unlike the split-toggle button below, a plain click never
                  // reassigns which pane an already-visible tab occupies.
                  if (key === activeKey || key === splitKey) return;
                  flushPendingEdits();
                  placeInPane('left', key);
                }
              },
              el('span.code-tab-name', null, tab.name.replace(/^assets\//, '')),
              dirty ? el('span.code-tab-dot') : null,
              // Not for the primary (left) pane's own tab: there is nothing to
              // open into the split for a tab that is already showing there,
              // and toggleSplit() would silently no-op on it.
              tabs.length > 1 && key !== activeKey
                ? el(
                    'button.code-tab-split',
                    {
                      class: key === splitKey ? 'active' : '',
                      title: key === splitKey ? 'Close split pane' : 'Open in split pane',
                      onclick: (event) => {
                        event.stopPropagation();
                        toggleSplit(tab);
                      }
                    },
                    '⧉'
                  )
                : null,
              el(
                'button.code-tab-close',
                {
                  title: 'Close',
                  onclick: (event) => {
                    event.stopPropagation();
                    closeTab(tab);
                  }
                },
                '×'
              )
            );
          })
        : el('div.code-tabs-empty', null, 'No file open')
    );
  }

  // ------------------------------------------------------------ the tree

  function treeRow(kind, name, { badge = null, action = null, label = name } = {}) {
    const key = tabKey(kind, name);
    return el(
      'div.tree-row',
      { class: key === activeKey ? 'active' : '', onclick: () => openFile(kind, name) },
      el('span.tree-name', { title: name }, label),
      badge ? el('span.tree-badge', null, badge) : null,
      action
        ? el(
            'button.tree-action',
            {
              title: action.title,
              onclick: (event) => {
                event.stopPropagation();
                action.run();
              }
            },
            action.glyph
          )
        : null
    );
  }

  async function revert(name) {
    const confirmed = await confirmModal(
      `Revert ${name}?`,
      'Your changes to this file are discarded and the engine’s original is used again. This can be undone.',
      'Revert'
    );
    if (!confirmed) return;
    // Drop the buffer first, or the open tab's next commit writes the override
    // straight back.
    const tab = tabs.find((entry) => entry.kind === 'engine' && entry.name === name);
    store.commit(`Revert ${name}`, (project) => {
      const index = project.code.overrides.findIndex((entry) => entry.name === name);
      if (index >= 0) project.code.overrides.splice(index, 1);
    });
    if (tab) {
      const stock = await readStock(name);
      tab.editor.setValue(stock);
      tab.committed = stock;
    }
    renderPanes();
    toast(`${name} is back to the original.`, 'info');
  }

  async function newFile() {
    // The engine list decides whether a name collides with a stock file, and it
    // arrives asynchronously.
    await engineReady;
    if (codeSlice().files.length >= CODE_LIMITS.files) {
      return toast(
        `A project can hold ${CODE_LIMITS.files} of your own code files, and this one is full. ` +
          'Delete one first.',
        'error'
      );
    }
    const name = await promptModal(
      'New code file',
      'File name — letters, numbers, dashes and underscores, ending in .asm',
      '',
      'Create'
    );
    if (!name) return;
    if (!CODE_FILE_RE.test(name)) {
      return toast('That name needs to end in .asm and contain no slashes.', 'error');
    }
    if (engineFiles.some((file) => file.name === name)) {
      return toast(`${name} is an engine file. Pick another name, or edit that file directly.`, 'error');
    }
    if (findFile('files', name)) return toast(`${name} already exists.`, 'error');

    const text =
      `; ${name} -- your own code, assembled into the fixed bank at $C000.\n` +
      '; Call a label in here from any engine file you have edited:  jsr my_routine\n' +
      '\n' +
      'my_routine:\n' +
      '  rts\n';
    store.commit(`Create ${name}`, (project) => {
      project.code.files.push({ name, text });
      project.code.files.sort((a, b) => a.name.localeCompare(b.name));
    });
    await openFile('user', name);
    renderTree();
  }

  async function deleteFile(name) {
    const confirmed = await confirmModal(
      `Delete ${name}?`,
      'The file is removed from this project. This can be undone.',
      'Delete'
    );
    if (!confirmed) return;
    // Closing normally commits, which would recreate what we are about to delete.
    const tab = tabs.find((entry) => entry.kind === 'user' && entry.name === name);
    if (tab) closeTab(tab, { commit: false });
    store.commit(`Delete ${name}`, (project) => {
      const index = project.code.files.findIndex((entry) => entry.name === name);
      if (index >= 0) project.code.files.splice(index, 1);
    });
    renderTree();
    renderPanes();
  }

  async function refreshGenerated() {
    if (!store.dir) return;
    const result = await window.forge.code.generatedFiles(store.dir);
    generatedFiles = result.ok ? result.value : [];
    renderTree();
  }

  function renderTree() {
    const { overrides, files } = codeSlice();
    const overridden = new Set(overrides.map((file) => file.name));

    fill(
      treeHost,
      el(
        'div.tree-group',
        null,
        el('div.tree-head', null, el('span', null, 'Engine'), el('span.tree-count', null, String(engineFiles.length))),
        engineFiles.map((file) =>
          treeRow('engine', file.name, {
            badge: overridden.has(file.name) ? 'edited' : null,
            action: overridden.has(file.name)
              ? { glyph: '↺', title: `Revert ${file.name} to the original`, run: () => revert(file.name) }
              : null
          })
        )
      ),
      el(
        'div.tree-group',
        null,
        el(
          'div.tree-head',
          null,
          el('span', null, 'Your files'),
          el('button.tree-add', { title: 'New code file', onclick: newFile }, '+')
        ),
        files.length
          ? files.map((file) =>
              treeRow('user', file.name, {
                action: { glyph: '×', title: `Delete ${file.name}`, run: () => deleteFile(file.name) }
              })
            )
          : el('div.tree-empty', null, 'None yet. Add one with +.')
      ),
      el(
        'div.tree-group',
        null,
        el(
          'div.tree-head',
          null,
          el('span', null, 'Generated'),
          el('button.tree-add', { title: 'Refresh', onclick: refreshGenerated }, '⟳')
        ),
        generatedFiles.length
          ? generatedFiles.map((name) =>
              treeRow('generated', name, { label: name.replace(/^assets\//, '') })
            )
          : el('div.tree-empty', null, 'Build the project to see what it generates.')
      )
    );
  }

  // ------------------------------------------------------------ shell

  const root = el(
    'div.forge',
    { style: { gridTemplateColumns: '240px 1fr' } },
    el('div.panel', null, el('div.panel-head', null, 'Files'), el('div.panel-body.tree-body', null, treeHost)),
    el(
      'div.panel',
      null,
      el('div.panel-head.code-head', null, tabsHost),
      el('div.panel-body.code-body', null, panesHost)
    )
  );

  container.append(root);
  renderTree();
  renderPanes();
  app.setMeta('Code Forge');

  // Kept, not just fired: anything that has to *know* whether a name is a stock
  // engine file — the new-file check, and the build panel's deep link into an
  // error — has to wait for it. A deep link arrives the moment this Forge mounts,
  // which is exactly when the list is still empty.
  const engineReady = window.forge.code.engineFiles().then((result) => {
    if (result.ok) engineFiles = result.value;
    renderTree();
  });
  refreshGenerated();

  return {
    destroy() {
      flushPendingEdits();
      for (const tab of tabs) tab.editor.destroy();
      app.setMeta('');
    },
    flushPendingEdits,
    hasPendingEdits: () => tabs.some(tabDirty),
    onProjectChange() {
      // An undo, a redo, or an edit from somewhere else. Re-read every open tab
      // from the project — except one whose buffer is mid-edit and already
      // matches what was committed, which is the tab that caused this.
      for (const tab of [...tabs]) {
        if (tab.kind === 'generated') continue;

        if (tab.kind === 'user') {
          const file = findFile('files', tab.name);
          // Nothing behind the tab any more — an undone Create, or a Delete from
          // elsewhere. Left open it stays editable, and every later commit looks
          // for a file that is not there and drops the edit on the floor.
          if (!file) closeTab(tab, { commit: false });
          else syncTab(tab, file.text);
          continue;
        }

        const override = findFile('overrides', tab.name);
        if (override) {
          syncTab(tab, override.text);
          continue;
        }
        // No override left, so the tab shows the stock file again. It may never
        // have been fetched — a tab opened on an already-overridden file reads
        // the override and never touches the original — so fetch it before
        // deciding, rather than leaving the edit on screen as if it survived.
        const stock = stockText.get(tab.name);
        if (stock !== undefined) {
          syncTab(tab, stock);
          continue;
        }
        readStock(tab.name).then(
          (text) => {
            // The project may have moved on again while that was in flight.
            if (!tabs.includes(tab) || findFile('overrides', tab.name)) return;
            syncTab(tab, text);
            renderTabs();
          },
          () => {}
        );
      }
      renderPanes();
      notePending();
    },
    /**
     * Open a file the build reported an error in. Names arrive as the assembler
     * saw them, relative to the build folder — which is why overrides are written
     * there under their own names and with their own line numbers.
     */
    async openFile(name, line = 0) {
      await engineReady;
      const bare = name.replace(/^.*[/\\]/, '');
      if (name.startsWith('assets/') || bare.endsWith('.inc')) {
        await refreshGenerated();
        const match = generatedFiles.find((file) => file === name || file.endsWith(`/${bare}`));
        if (match) return openFile('generated', match, line);
      }
      if (engineFiles.some((file) => file.name === bare)) return openFile('engine', bare, line);
      if (findFile('files', bare)) return openFile('user', bare, line);
      toast(`${name} is not a file the Code Forge can open.`, 'warn');
      return null;
    }
  };
}
