// Code Forge: the escape hatch. Every source file that goes into the ROM, in a
// tree on the left and tabbed editors on the right.
//
// Three kinds of file, and the difference between them is the whole design:
//
//  - **Engine** files are the app's own 6502 sources. Editing one does not touch
//    them: the edit is saved into the *project* as an override, and the build
//    lays it over the stock copy. So one project's custom code cannot leak into
//    another, and reverting is deleting the copy.
//  - **Your files** are new sources the project owns outright. The generator
//    lists them in assets/usercode.inc, which engine/main.asm includes in the
//    fixed kernel — so a label defined here can be called from anywhere.
//  - **Generated** files are the build's own output, read-only because the next
//    build deletes and rewrites the whole folder.
//
// Edits live in `store.project.code`, which is what gives them undo, the dirty
// dot and saving without inventing a second version of any of it. A code editor
// never blurs, so instead of committing per keystroke (an unusable undo stack)
// or on blur (a commit that may never come), typing commits once it pauses.

import { store } from '../../store.js';
import { el, fill, toast, confirmModal, promptModal } from '../../ui.js';
import { CODE_FILE_RE } from '../../../shared/project.js';
import { createEditor } from './editor.js';

/** How long typing has to pause before it becomes one undo entry. */
const COMMIT_DELAY = 600;

const HINTS = {
  stock:
    'Editing this makes a copy inside your project. The app’s own engine is left alone, and you can ' +
    'revert to the original at any time.',
  override: 'Your project’s copy of this engine file. The build uses this instead of the original.',
  user:
    'Your own code, assembled into the fixed bank at $C000. Call a label in here with jsr from any ' +
    'engine file you have edited.',
  generated: 'Generated by the build from your project. Read-only — the next build rewrites it.'
};

export function mount(container, app) {
  // Stock engine sources, fetched once each and kept for the session: they are
  // read-only inputs that cannot change while the app runs, and comparing
  // against them is how an override knows whether it still differs.
  const stockText = new Map();
  let engineFiles = [];
  let generatedFiles = [];

  /** Open tabs, in strip order. */
  const tabs = [];
  let activeKey = null;
  let pendingCommit = null;

  const treeHost = el('div.code-tree');
  const tabsHost = el('div.tabs.code-tabs');
  const hintHost = el('div.code-hint');
  const editorHost = el('div.code-host');

  const codeSlice = () => store.project?.code ?? { overrides: [], files: [] };
  const findFile = (group, name) => codeSlice()[group].find((file) => file.name === name) ?? null;
  const tabKey = (kind, name) => `${kind}:${name}`;
  const activeTab = () => tabs.find((tab) => tabKey(tab.kind, tab.name) === activeKey) ?? null;

  // ------------------------------------------------------------ file access

  async function readStock(name) {
    if (stockText.has(name)) return stockText.get(name);
    const response = await fetch(`forge://app/engine/${name}`);
    if (!response.ok) throw new Error(`Could not read the engine's ${name}.`);
    const text = await response.text();
    stockText.set(name, text);
    return text;
  }

  /** The text a tab should show, and whether the user may edit it. */
  async function loadText(kind, name) {
    if (kind === 'generated') {
      const result = await window.forge.code.readGenerated(store.dir, name);
      if (!result.ok) throw new Error(result.error);
      return result.value;
    }
    if (kind === 'user') return findFile('files', name)?.text ?? '';
    return findFile('overrides', name)?.text ?? (await readStock(name));
  }

  // ------------------------------------------------------------ committing

  /**
   * Write a tab's buffer into the project. An engine file becomes an override
   * the first time it differs from stock — and stops being one the moment it
   * matches again, so undoing an experiment by hand leaves no trace behind.
   */
  function commitTab(tab) {
    const text = tab.editor.getValue();
    if (text === tab.committed) return;
    const name = tab.name;

    if (tab.kind === 'user') {
      store.commit(`Edit ${name}`, (project) => {
        const file = project.code.files.find((entry) => entry.name === name);
        if (file) file.text = text;
      });
    } else {
      const stock = stockText.get(name);
      const matchesStock = stock !== undefined && text === stock;
      store.commit(matchesStock ? `Revert ${name}` : `Edit ${name}`, (project) => {
        const index = project.code.overrides.findIndex((entry) => entry.name === name);
        if (matchesStock) {
          if (index >= 0) project.code.overrides.splice(index, 1);
        } else if (index >= 0) {
          project.code.overrides[index].text = text;
        } else {
          project.code.overrides.push({ name, text });
          project.code.overrides.sort((a, b) => a.name.localeCompare(b.name));
        }
      });
    }
    tab.committed = text;
    renderTree();
    renderTabs();
  }

  function scheduleCommit(tab) {
    clearTimeout(pendingCommit);
    renderTabs(); // the dot appears as soon as the buffer differs
    pendingCommit = setTimeout(() => {
      pendingCommit = null;
      commitTab(tab);
    }, COMMIT_DELAY);
  }

  /** Commit every tab now — before a save, a tab switch, or leaving the Forge. */
  function flushPendingEdits() {
    clearTimeout(pendingCommit);
    pendingCommit = null;
    for (const tab of tabs) if (tab.kind !== 'generated') commitTab(tab);
  }

  // ------------------------------------------------------------ tabs

  async function openFile(kind, name, line = 0) {
    const key = tabKey(kind, name);
    const existing = tabs.find((tab) => tabKey(tab.kind, tab.name) === key);
    if (existing) {
      activeKey = key;
      showActive();
      if (line) existing.editor.gotoLine(line);
      existing.editor.markLine(line);
      return existing;
    }

    let text;
    try {
      text = await loadText(kind, name);
    } catch (error) {
      toast(error.message, 'error');
      return null;
    }

    const tab = { kind, name, committed: text, editor: null };
    tab.editor = createEditor({
      value: text,
      readOnly: kind === 'generated',
      onChange: () => scheduleCommit(tab)
    });
    tabs.push(tab);
    activeKey = key;
    showActive();
    if (line) {
      tab.editor.gotoLine(line);
      tab.editor.markLine(line);
    }
    return tab;
  }

  function closeTab(tab) {
    if (tab.kind !== 'generated') commitTab(tab);
    const index = tabs.indexOf(tab);
    tabs.splice(index, 1);
    tab.editor.destroy();
    if (activeKey === tabKey(tab.kind, tab.name)) {
      const next = tabs[index] ?? tabs[index - 1] ?? null;
      activeKey = next ? tabKey(next.kind, next.name) : null;
    }
    showActive();
  }

  function showActive() {
    const tab = activeTab();
    renderTabs();
    renderTree();
    if (!tab) {
      fill(hintHost);
      hintHost.hidden = true;
      fill(
        editorHost,
        el(
          'div.placeholder',
          null,
          el('div.placeholder-glyph', null, '‹›'),
          el('h2', null, 'The code behind your game'),
          el(
            'p',
            null,
            'Pick a file on the left. Engine files are the app’s own 6502 source — editing one keeps ' +
              'your changes in this project, so the original is always there to go back to.'
          )
        )
      );
      return;
    }
    const kind =
      tab.kind === 'generated'
        ? 'generated'
        : tab.kind === 'user'
          ? 'user'
          : findFile('overrides', tab.name)
            ? 'override'
            : 'stock';
    hintHost.hidden = false;
    fill(hintHost, HINTS[kind]);
    // Only when it actually changes. Removing and re-appending a node blurs
    // whatever inside it had focus, and this runs on every commit — including the
    // debounced one a few hundred milliseconds into typing, which would take the
    // caret away mid-sentence.
    if (editorHost.firstChild !== tab.editor.el) fill(editorHost, tab.editor.el);
  }

  function renderTabs() {
    fill(
      tabsHost,
      tabs.length
        ? tabs.map((tab) => {
            const key = tabKey(tab.kind, tab.name);
            const dirty = tab.kind !== 'generated' && tab.editor.getValue() !== tab.committed;
            return el(
              'div.tab.code-tab',
              {
                class: key === activeKey ? 'active' : '',
                title: tab.kind === 'generated' ? `${tab.name} (generated)` : tab.name,
                onclick: () => {
                  if (key === activeKey) return;
                  flushPendingEdits();
                  activeKey = key;
                  showActive();
                }
              },
              el('span.code-tab-name', null, tab.name.replace(/^assets\//, '')),
              dirty ? el('span.code-tab-dot') : null,
              el(
                'button.code-tab-close',
                {
                  title: 'Close',
                  onclick: (event) => {
                    event.stopPropagation();
                    closeTab(tab);
                  }
                },
                '×'
              )
            );
          })
        : el('div.code-tabs-empty', null, 'No file open')
    );
  }

  // ------------------------------------------------------------ the tree

  function treeRow(kind, name, { badge = null, action = null, label = name } = {}) {
    const key = tabKey(kind, name);
    return el(
      'div.tree-row',
      { class: key === activeKey ? 'active' : '', onclick: () => openFile(kind, name) },
      el('span.tree-name', { title: name }, label),
      badge ? el('span.tree-badge', null, badge) : null,
      action
        ? el(
            'button.tree-action',
            {
              title: action.title,
              onclick: (event) => {
                event.stopPropagation();
                action.run();
              }
            },
            action.glyph
          )
        : null
    );
  }

  async function revert(name) {
    const confirmed = await confirmModal(
      `Revert ${name}?`,
      'Your changes to this file are discarded and the engine’s original is used again. This can be undone.',
      'Revert'
    );
    if (!confirmed) return;
    // Drop the buffer first, or the open tab's next commit writes the override
    // straight back.
    const tab = tabs.find((entry) => entry.kind === 'engine' && entry.name === name);
    store.commit(`Revert ${name}`, (project) => {
      const index = project.code.overrides.findIndex((entry) => entry.name === name);
      if (index >= 0) project.code.overrides.splice(index, 1);
    });
    if (tab) {
      const stock = await readStock(name);
      tab.editor.setValue(stock);
      tab.committed = stock;
    }
    renderTree();
    renderTabs();
    showActive();
    toast(`${name} is back to the original.`, 'info');
  }

  async function newFile() {
    const name = await promptModal(
      'New code file',
      'File name — letters, numbers, dashes and underscores, ending in .asm',
      '',
      'Create'
    );
    if (!name) return;
    if (!CODE_FILE_RE.test(name)) {
      return toast('That name needs to end in .asm and contain no slashes.', 'error');
    }
    if (engineFiles.some((file) => file.name === name)) {
      return toast(`${name} is an engine file. Pick another name, or edit that file directly.`, 'error');
    }
    if (findFile('files', name)) return toast(`${name} already exists.`, 'error');

    const text =
      `; ${name} -- your own code, assembled into the fixed bank at $C000.\n` +
      '; Call a label in here from any engine file you have edited:  jsr my_routine\n' +
      '\n' +
      'my_routine:\n' +
      '  rts\n';
    store.commit(`Create ${name}`, (project) => {
      project.code.files.push({ name, text });
      project.code.files.sort((a, b) => a.name.localeCompare(b.name));
    });
    await openFile('user', name);
    renderTree();
  }

  async function deleteFile(name) {
    const confirmed = await confirmModal(
      `Delete ${name}?`,
      'The file is removed from this project. This can be undone.',
      'Delete'
    );
    if (!confirmed) return;
    const tab = tabs.find((entry) => entry.kind === 'user' && entry.name === name);
    if (tab) {
      // Closing commits, which would recreate what we are about to delete.
      tab.committed = tab.editor.getValue();
      closeTab(tab);
    }
    store.commit(`Delete ${name}`, (project) => {
      const index = project.code.files.findIndex((entry) => entry.name === name);
      if (index >= 0) project.code.files.splice(index, 1);
    });
    renderTree();
    showActive();
  }

  async function refreshGenerated() {
    if (!store.dir) return;
    const result = await window.forge.code.generatedFiles(store.dir);
    generatedFiles = result.ok ? result.value : [];
    renderTree();
  }

  function renderTree() {
    const { overrides, files } = codeSlice();
    const overridden = new Set(overrides.map((file) => file.name));

    fill(
      treeHost,
      el(
        'div.tree-group',
        null,
        el('div.tree-head', null, el('span', null, 'Engine'), el('span.tree-count', null, String(engineFiles.length))),
        engineFiles.map((file) =>
          treeRow('engine', file.name, {
            badge: overridden.has(file.name) ? 'edited' : null,
            action: overridden.has(file.name)
              ? { glyph: '↺', title: `Revert ${file.name} to the original`, run: () => revert(file.name) }
              : null
          })
        )
      ),
      el(
        'div.tree-group',
        null,
        el(
          'div.tree-head',
          null,
          el('span', null, 'Your files'),
          el('button.tree-add', { title: 'New code file', onclick: newFile }, '+')
        ),
        files.length
          ? files.map((file) =>
              treeRow('user', file.name, {
                action: { glyph: '×', title: `Delete ${file.name}`, run: () => deleteFile(file.name) }
              })
            )
          : el('div.tree-empty', null, 'None yet. Add one with +.')
      ),
      el(
        'div.tree-group',
        null,
        el(
          'div.tree-head',
          null,
          el('span', null, 'Generated'),
          el('button.tree-add', { title: 'Refresh', onclick: refreshGenerated }, '⟳')
        ),
        generatedFiles.length
          ? generatedFiles.map((name) =>
              treeRow('generated', name, { label: name.replace(/^assets\//, '') })
            )
          : el('div.tree-empty', null, 'Build the project to see what it generates.')
      )
    );
  }

  // ------------------------------------------------------------ shell

  const root = el(
    'div.forge',
    { style: { gridTemplateColumns: '240px 1fr' } },
    el('div.panel', null, el('div.panel-head', null, 'Files'), el('div.panel-body.tree-body', null, treeHost)),
    el(
      'div.panel',
      null,
      el('div.panel-head.code-head', null, tabsHost),
      el('div.panel-body.code-body', null, hintHost, editorHost)
    )
  );

  container.append(root);
  renderTree();
  showActive();
  app.setMeta('Code Forge');

  window.forge.code.engineFiles().then((result) => {
    if (result.ok) engineFiles = result.value;
    renderTree();
  });
  refreshGenerated();

  return {
    destroy() {
      flushPendingEdits();
      for (const tab of tabs) tab.editor.destroy();
      app.setMeta('');
    },
    flushPendingEdits,
    onProjectChange() {
      // An undo, a redo, or an edit from somewhere else. Re-read every open tab
      // from the project — except one whose buffer is mid-edit and already
      // matches what was committed, which is the tab that caused this.
      for (const tab of tabs) {
        if (tab.kind === 'generated') continue;
        const stored =
          tab.kind === 'user'
            ? findFile('files', tab.name)?.text
            : findFile('overrides', tab.name)?.text ?? stockText.get(tab.name);
        if (stored === undefined || stored === tab.committed) continue;
        tab.editor.setValue(stored);
        tab.committed = stored;
      }
      renderTree();
      renderTabs();
      showActive();
    },
    /**
     * Open a file the build reported an error in. Names arrive as the assembler
     * saw them, relative to the build folder — which is why overrides are written
     * there under their own names and with their own line numbers.
     */
    async openFile(name, line = 0) {
      const bare = name.replace(/^.*[/\\]/, '');
      if (name.startsWith('assets/') || bare.endsWith('.inc')) {
        await refreshGenerated();
        const match = generatedFiles.find((file) => file === name || file.endsWith(`/${bare}`));
        if (match) return openFile('generated', match, line);
      }
      if (engineFiles.some((file) => file.name === bare)) return openFile('engine', bare, line);
      if (findFile('files', bare)) return openFile('user', bare, line);
      toast(`${name} is not a file the Code Forge can open.`, 'warn');
      return null;
    }
  };
}
